#pragma once
#include <cereal\types\memory.hpp>
#include <cereal\archives\binary.hpp>
#include <cereal\types\unordered_map.hpp>
#include <cereal\types\map.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/list.hpp>
#include <cereal\access.hpp>
#include <cereal\cereal.hpp>
